/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/income/{userId}": {
    patch: operations["boardIncome"];
    parameters: {
      path: {
        userId: number;
      };
    };
  };
  "/mail": {
    get: operations["getMail"];
  };
}

export interface components {
  schemas: {
    /** Mail */
    Mail: {
      content: string;
      mainIcon: string;
      subIcon?: string;
      buttonContent?: string;
      buttonEffect: {
        url?: string;
        items?: {
          rewardType?: string;
          rewardCount?: number;
        }[];
      };
      args?: { [key: string]: unknown };
      expireTime: number;
      sendTime?: number;
    };
  };
}

export interface operations {
  boardIncome: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  getMail: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Mail"][];
        };
      };
    };
  };
}

export interface external {}


import { AsgardClient , options} from "@imf/asgard-client";

export class Api {

    public asgardClient: AsgardClient
  
    constructor(asgardClient:AsgardClient) {
      this.asgardClient = asgardClient
    }
  
    connect() {
      this.asgardClient.connect()
    }
  
  
    

    /**
     * 
     * 新邮件广播
     */
    boardIncome(parameter:operations["boardIncome"]["parameters"]["path"],options?:options,){
    
      return this.asgardClient.broadcast<operations["boardIncome"]["responses"]["200"]["content"]["application/json"]>(`/mail/income/${parameter["userId"]}`,{},options??options)
    

     }   
      
    

    /**
     * 
     * 邮件
     */
    getMail(options?:options,){
    
      return this.asgardClient.get<operations["getMail"]["responses"]["200"]["content"]["application/json"]>("/mail/mail",{},options??options)
    

     }   
      
}
